name: Doctor PR
description: Address code reviews automatically with AI
author: "Doctor PR"
branding:
  icon: "git-merge"
  color: "black"
inputs:
  base_branch_name:
    required: true
    description: The name of the branch to merge into

  base_pull_request_number:
    required: true
    description: The number of the pull request to merge into

  review_id:
    required: true
    description: The ID of the review to address

  author_username:
    required: true
    description: The GitHub username of the PR author

  aider_args:
    required: true
    description: Command line arguments to pass to Aider

  aider_api_key:
    required: true
    description: The API key to use for Aider

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Configure Git
      shell: bash
      run: |
        git config --global user.email 202363839+Doctor-PR[bot]@users.noreply.github.com
        git config --global user.name Doctor-PR[bot]
    - name: Install Aider
      shell: bash
      run: curl -LsSf https://aider.chat/install.sh | sh
    - name: Run Aider
      id: run_aider
      shell: bash
      env:
        AIDER_API_KEY: ${{inputs.aider_api_key}}
      run: |
        # Create a directory outside the Git repository
        mkdir -p /tmp/aider
        # Run aider and capture its output to a file outside the repo while also displaying it
        aider ${{inputs.aider_args}} | tee /tmp/aider/output.txt
        # Store the output as a step output
        echo "aider_output<<EOF" >> $GITHUB_OUTPUT
        cat /tmp/aider/output.txt >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    - name: Extract Commit Message
      id: extract_commit
      shell: bash
      run: node ${{ github.action_path }}/scripts/extract-commit.js
    - name: Create Pull Request
      if: steps.extract_commit.outputs.changes_made == 'true'
      uses: peter-evans/create-pull-request@v7
      with:
        base: ${{inputs.base_branch_name}}
        branch: "${{inputs.base_branch_name}}-fix-${{inputs.review_id}}"
        reviewers: ${{inputs.author_username}}
        title: ${{steps.extract_commit.outputs.commit_message}}
        body: |
          Address [review comment][1] for PR #${{inputs.base_pull_request_number}}
          Auto-generated by Doctor PR[bot]

          [1]: https://github.com/${{github.repository}}/pull/${{inputs.base_pull_request_number}}#pullrequestreview-${{inputs.review_id}}
