name: Doctor PR
description: Address code reviews automatically with AI
author: "Doctor PR"
branding:
  icon: "git-merge"
  color: "black"
inputs:
  action_input:
    required: true
    description: The encoded input to pass to the action
  anthropic_api_key:
    required: true
    description: The API key to use for Anthropic

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Configure Git
      shell: bash
      run: |
        git config --global user.email 202363839+Doctor-PR[bot]@users.noreply.github.com
        git config --global user.name Doctor-PR[bot]
    - name: Decode Inputs
      shell: bash
      env:
        ACTION_INPUT: ${{inputs.action_input}}
      run: node ${{ github.action_path }}/lib/decode-inputs.js
    - name: Install Aider
      shell: bash
      run: curl -LsSf https://aider.chat/install.sh | sh
    - name: Run Aider
      id: run_aider
      shell: bash
      env:
        ANTHROPIC_API_KEY: ${{inputs.anthropic_api_key}}
      run: |
        # Create a directory outside the Git repository
        mkdir -p /tmp/aider
        # Run aider and capture its output to a file outside the repo while also displaying it
        aider $aider_args | tee /tmp/aider/output.txt
        # Store the output as a step output
        echo "aider_output<<EOF" >> $GITHUB_OUTPUT
        cat /tmp/aider/output.txt >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    - name: Extract Commit Message
      id: extract_commit
      shell: bash
      run: node ${{ github.action_path }}/lib/extract-commit.js
    - name: Create Pull Request
      if: steps.extract_commit.outputs.changes_made == 'true'
      uses: peter-evans/create-pull-request@v7
      with:
        base: ${{env.base_branch_name}}
        branch: "${{env.base_branch_name}}-fix-${{env.review_id}}"
        reviewers: ${{env.author_username}}
        title: ${{steps.extract_commit.outputs.commit_message}}
        body: |
          Address [review comment][1] for PR #${{env.base_pull_request_number}}
          Auto-generated by Doctor PR[bot]

          [1]: https://github.com/${{github.repository}}/pull/${{env.base_pull_request_number}}#pullrequestreview-${{env.review_id}}
