name: Doctor PR
description: Address code reviews automatically with AI
author: "Doctor PR"
branding:
  icon: "git-merge"
  color: "black"
inputs:
  base_branch_name:
    required: true
    description: The name of the branch to merge into

  base_pull_request_number:
    required: true
    description: The number of the pull request to merge into

  review_id:
    required: true
    description: The ID of the review to address

  aider_message:
    required: true
    description: The message to send to Aider

  author_username:
    required: true
    description: The GitHub username of the PR author

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Configure Git
      shell: bash
      run: |
        git config --global user.email ${{env.GIT_USER_EMAIL}}
        git config --global user.name ${{env.GIT_USER_NAME}}
    - name: Install Aider
      shell: bash
      run: curl -LsSf https://aider.chat/install.sh | sh
    - name: Run Aider
      id: run_aider
      shell: bash
      run: |
        # Create a directory outside the Git repository
        mkdir -p /tmp/aider
        # Run aider and capture its output to a file outside the repo while also displaying it
        aider | tee /tmp/aider/output.txt
        # Store the output as a step output
        echo "aider_output<<EOF" >> $GITHUB_OUTPUT
        cat /tmp/aider/output.txt >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    - name: Extract Commit Message
      id: extract_commit
      shell: bash
      run: |
        # Search for the commit message pattern in the entire output file
        COMMIT_LINE=$(grep -E "Commit [a-f0-9]+ " /tmp/aider/output.txt | tail -n 1)

        if [ -n "$COMMIT_LINE" ]; then
          # Extract the commit message from the line
          COMMIT_MESSAGE=$(echo "$COMMIT_LINE" | sed -E 's/Commit [a-f0-9]+ (.*)/\1/')
        else
          # Fallback if no commit message is found
          COMMIT_MESSAGE="Fix from Fix PR[bot]"
        fi

        # Remove any quotes that might cause issues
        COMMIT_MESSAGE=$(echo "$COMMIT_MESSAGE" | tr -d '"')
        echo "commit_message=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
        # For debugging
        echo "Extracted commit message: $COMMIT_MESSAGE"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        base: ${{inputs.base_branch_name}}
        branch: "${{inputs.base_branch_name}}-fix-${{inputs.review_id}}"
        author: "${{env.GIT_USER_NAME}} <${{env.GIT_USER_EMAIL}}>"
        committer: "${{env.GIT_USER_NAME}} <${{env.GIT_USER_EMAIL}}>"
        reviewers: ${{inputs.author_user_name}}
        title: ${{steps.extract_commit.outputs.commit_message}}
        body: |
          Address [review comment][1] for PR #${{inputs.base_pull_request_number}}
          Auto-generated by ${{env.GIT_USER_NAME}}

          [1]: https://github.com/${{github.repository}}/pull/${{inputs.base_pull_request_number}}#pullrequestreview-${{inputs.review_id}}
